name       : python-prometheus_client
version    : 0.15.0
release    : 7
source     :
    - https://github.com/prometheus/client_python/archive/refs/tags/v0.15.0.tar.gz : f03a6701eb966ae160947ba664e0f117aed783a7516ebf7bd2e7090285f81607
homepage   : https://github.com/prometheus/client_python
license    : Apache-2.0
component  : programming.python
summary    : Prometheus instrumentation library for Python applications
description: |
    Prometheus instrumentation library for Python applications
builddeps  :
    - python-pytest # check
    - python-twisted
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
