name       : python-prometheus_client
version    : 0.4.2
release    : 1
source     :
    - https://github.com/prometheus/client_python/archive/v0.4.2.tar.gz : 24d728f2630e396ed8bc2f2971788f7dcf1a839d5b05964a9b82d43a2e6e0b0e
license    : Apache-2.0
component  : programming.python
summary    : Prometheus instrumentation library for Python applications
description: |
    Prometheus instrumentation library for Python applications
builddeps  :
    - python-twisted
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
