name       : python-prometheus_client
version    : 0.12.0
release    : 4
source     :
    - https://github.com/prometheus/client_python/archive/refs/tags/v0.12.0.tar.gz : e334d2a4e5287ead716a8ad88ac612c99d7bdf7a28edca11c7e750dcd3d50307
license    : Apache-2.0
component  : programming.python
summary    : Prometheus instrumentation library for Python applications
description: |
    Prometheus instrumentation library for Python applications
builddeps  :
    - python-pytest # check
    - python-twisted
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
